### ISSUE TITLE
DNN Form And List 6.3.2 search problem

### ISSUE THREAD

**Issue by enfJoao** [SCullman/DNN.FormAndList#1]
Hey there.

I've been using you 6.3.2 version of DNN Form And List in DNN 9.0.2 and it works very well. Thank you very much for your effort into this module.

I found a small bug that I would like to report it to you:
Since the update to this version, when I activate search box (with or without simple search), it does not appear on the module/page. Lists created before the update still show the search box.

Best regards,
João Gomes

**Comment by SCullman** [comment]
Can you please attach a template?
You can create a template using "Save as a template". The template file is afterwards located in [Portalroot]\templates\[templatename].dnn_userdefinedtable.module.template.

**Comment by enfJoao** [comment]
Sent privately.

**Comment by SCullman** [comment]
Thanks. I am now able to reproduce the issue.

**Comment by enfJoao** [comment]
Nice.
Looking forward for your great work in this module.
Specially if we're talking about customs forms in edit record also :)
Best regards,
João

**Comment by SCullman** [comment]
None of the fields in the provided template have been marked as _searchable_. 
Form and List works as expected and hides search boxes if none of its fields can be used within search.
