### ISSUE TITLE
Suchfeld

### ISSUE THREAD

**Issue by Eicheljaner** [SCullman/DNN.FormAndList#2]
Was mir noch aufgefallen ist, was nicht schön aus sieht, ist wenn man in der Liste das Suchfeld aktiviert.
Unter dem Suchfeld ist zu wenig Platz, die Liste stößt an das Suchfeld.
![formandlist_suchfeld](https://cloud.githubusercontent.com/assets/28135670/25518609/bec79544-2bf4-11e7-8e6f-dfae549559d1.jpg)

**Comment by SCullman** [comment]
Wie wärs, im Portal.css oder im Skin sich mit CSS den Platz zu schaffen? Dafür braucht man nicht unbedingt eine Änderung im Modul.

**Comment by Eicheljaner** [comment]
Ja möglich ist es immer. Es ist doch schön wenn man ein Modul gleich nutzen kann und nicht immer noch, ich sage mal dazu "Schönheitsfehler" ausbessern muss, es ist immer mit Zeit verbunden die man für was anderes nutzen kann. Eine CSS zu veränder oder anzupassen bin ich der Meinung, ändert man wenn man das Modul zu sein Design ändern möchte. Ich habe schon einige Module benutzt, die von der Idee toll sind, aber das Aussehen eine  Katastrophe sind. Bitte verstehe mich nicht falsch, ich weiß das so ein Modul viel Arbeit macht, aber wenn es um DNN Erscheinungsbild geht, hört das Aussehen dazu. DNN ohne Module ist nichts.  Gruß Sven

**Comment by SCullman** [comment]
Ich habe Form and List vor gefühlten Ewigkeiten in andere Hände gegeben. Das sich keiner mehr für den offiziellen Branch verantwortlich fühlt, macht mich zwar traurig, ich will aber hiermit nicht mehr die (DNN-) Welt  verbessern, das ist nicht mehr mein Anspruch. Das hier ist mein eigener Fork, hier kann ich tun und _lassen_, was ich will. 

Ich würde  einen PullRequest mit einem Fix gerne in Augenschein nehmen..

**Comment by SCullman** [comment]
Will be fixed in fnl6.4.0
