### ISSUE TITLE
Date field with current date as default

### ISSUE THREAD

**Issue by enfJoao** [SCullman/DNN.FormAndList#3]
Hey.

Is it possible to create a date field with the current date as the default value, but still able to change in the calendar?

Best regards,
João Gomes

**Comment by SCullman** [comment]
Should be possible with a token. 

Gesendet von meinem Windows 10 Phone

Von: eXistenZe
Gesendet: Donnerstag, 3. August 2017 18:12
An: SCullman/DNN.FormAndList
Cc: Subscribed
Betreff: [SCullman/DNN.FormAndList] Date field with current date as default(#3)

Hey.
Is it possible to create a date field with the current date as the default value, but still able to change in the calendar?
Best regards,
João Gomes

**Comment by enfJoao** [comment]
Correct... DNN tokens work fine. Thanks a lot.
