### ISSUE TITLE
Using [fields] inside function in XSL script

### ISSUE THREAD

**Issue by enfJoao** [SCullman/DNN.FormAndList#5]
Hey there.
I'm trying to create a list with two rows for each RowId, first visible and second hidden with this code:

https://pastebin.mozilla.org/9029589

However once I place the token brackets in the onClick="toggle('[UserDefinedRowId]');" and click "generate from html template" I get this error:

RawUrl:/cc/10/page/ctl/GenerateXsl/mid/614/Edit/Current
Referrer:https://mysite.pt/cc/10/farmacossu/ctl/GenerateXsl/mid/614/Edit/Current
ExceptionHash:KXfcUjiSKeSKzbjkDs5CNxWZvVE=
Message:'<', hexadecimal value 0x3C, is an invalid attribute character. Line 149, position 30.

If I do not place the brackets in html, but edit the xslt script with {udt:UserDefinedRowId} it works just fine. This only happens inside the toggle function, everywhere else works fine.

Best regards,
João

**Comment by SCullman** [comment]
Cannot reproduce as there is no more info in the paste bin.
Just a guess: you cannot enter js in the html template. That is by design.

**Comment by enfJoao** [comment]
You can enter JS. You just can't use tokens in some places.

**Comment by SCullman** [comment]
Ok, but that is only by chance, and I would not recommend it.
If it works for you, then perfect. If it fails like for tokens, I will not spent any time fixing it.
